2021-06-21 22:07:52.845 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-21 22:07:52.857 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-21 22:07:52.870 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-21 22:07:52.870 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-21 22:07:52.870 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-21 22:07:52.870 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-21 22:07:52.952 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-21 22:07:52.952 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-21 22:07:52.961 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-21 22:07:52.967 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-21 22:07:52.984 [warning] <0.302.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-21 22:07:53.085 [error] <0.305.0>@Elixir.HVACDatabase.Pubsub.RabbitMQ:setup_queue:4 CRASH REPORT Process <0.305.0> with 0 neighbours exited with reason: no match of right hand value {error,channel_not_ready} in 'Elixir.HVACDatabase.Pubsub.RabbitMQ':setup_queue/2 line 4 in application_master:init/4 line 142
2021-06-21 22:09:12.907 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-21 22:09:12.917 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-21 22:09:12.925 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-21 22:09:12.925 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-21 22:09:12.925 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-21 22:09:12.925 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-21 22:09:12.995 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-21 22:09:12.995 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-21 22:09:13.007 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-21 22:09:13.016 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-21 22:09:13.032 [warning] <0.375.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-21 22:09:13.312 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:09:06.719 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:09:06.724 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:09:06.731 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:09:06.731 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:09:06.731 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:09:06.731 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:09:06.803 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:09:06.803 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:09:06.814 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:09:06.818 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:09:06.818 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:09:06.897 [warning] <0.359.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:09:07.103 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:09:07.128 [error] <0.389.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.389.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:09:07.128 [error] <0.386.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.386.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.388.0>, {<<"client 127.0.0.1:56666 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.389.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:09:07.128 [error] <0.386.0> Supervisor {<0.386.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.388.0>, {<<"client 127.0.0.1:56666 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.389.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:09:07.128 [error] <0.344.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.359.0> exit with reason {shutdown,{gen_server,call,[<0.388.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.359.0>},70000]}} in context child_terminated
2021-06-22 09:09:07.157 [error] <0.417.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.417.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:09:07.157 [error] <0.414.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.414.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.416.0>, {<<"client 127.0.0.1:56668 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.417.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:09:07.157 [error] <0.414.0> Supervisor {<0.414.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.416.0>, {<<"client 127.0.0.1:56668 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.417.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:09:07.157 [error] <0.344.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.391.0> exit with reason {shutdown,{gen_server,call,[<0.416.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.391.0>},70000]}} in context child_terminated
2021-06-22 09:09:07.186 [error] <0.444.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.444.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:09:07.186 [error] <0.441.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.441.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.443.0>, {<<"client 127.0.0.1:56670 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.444.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:09:07.186 [error] <0.441.0> Supervisor {<0.441.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.443.0>, {<<"client 127.0.0.1:56670 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.444.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:09:07.186 [error] <0.344.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.418.0> exit with reason {shutdown,{gen_server,call,[<0.443.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.418.0>},70000]}} in context child_terminated
2021-06-22 09:09:07.211 [error] <0.471.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.471.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:09:07.211 [error] <0.468.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.468.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.470.0>, {<<"client 127.0.0.1:56672 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.471.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:09:07.211 [error] <0.468.0> Supervisor {<0.468.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.470.0>, {<<"client 127.0.0.1:56672 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.471.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:09:07.211 [error] <0.344.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.445.0> exit with reason {shutdown,{gen_server,call,[<0.470.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.445.0>},70000]}} in context child_terminated
2021-06-22 09:09:07.211 [error] <0.344.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.445.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:09:07.213 [info] <0.44.0> Application hvac_database exited with reason: shutdown
2021-06-22 09:15:15.670 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:15:15.675 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:15:15.682 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:15:15.682 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:15:15.682 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:15:15.682 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:15:15.743 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:15:15.743 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:15:15.752 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:15:15.756 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:15:15.756 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:15:15.838 [warning] <0.328.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:15:17.931 [error] <0.313.0>@Elixir.HVACDatabase.Pubsub.RabbitMQ:setup_queue:25 Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.HVACDatabase.Pubsub.RabbitMQ':setup_queue/0 line 25 in context start_error
2021-06-22 09:15:17.931 [error] <0.328.0>@Elixir.HVACDatabase.Pubsub.RabbitMQ:setup_queue:25 CRASH REPORT Process <0.328.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.HVACDatabase.Pubsub.RabbitMQ':setup_queue/0 line 25
2021-06-22 09:15:17.931 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACDatabase.Pubsub.RabbitMQ',{{badmatch,{error,econnrefused}},[{'Elixir.HVACDatabase.Pubsub.RabbitMQ',setup_queue,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,25}]},{'Elixir.HVACDatabase.Pubsub.RabbitMQ',init,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,11}]},{'Elixir.GenRMQ.Publisher',init,1,[{file,"lib/publisher.ex"},{line,216}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_s..."},...]},...]}}},...} in application_master:init/4 line 142
2021-06-22 09:27:59.043 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:27:59.048 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:27:59.053 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:27:59.054 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:27:59.054 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:27:59.054 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:27:59.117 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:27:59.117 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:27:59.127 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:27:59.131 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:27:59.131 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:27:59.215 [warning] <0.338.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:27:59.513 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:27:59.534 [error] <0.369.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.369.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:27:59.534 [error] <0.366.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.366.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.368.0>, {<<"client 127.0.0.1:55682 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.369.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:27:59.534 [error] <0.366.0> Supervisor {<0.366.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.368.0>, {<<"client 127.0.0.1:55682 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.369.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:27:59.549 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.338.0> exit with reason {shutdown,{gen_server,call,[<0.368.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in context child_terminated
2021-06-22 09:27:59.579 [error] <0.397.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.397.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:27:59.579 [error] <0.394.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.394.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.396.0>, {<<"client 127.0.0.1:55684 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.397.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:27:59.579 [error] <0.394.0> Supervisor {<0.394.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.396.0>, {<<"client 127.0.0.1:55684 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.397.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:27:59.579 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.371.0> exit with reason {shutdown,{gen_server,call,[<0.396.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.371.0>},70000]}} in context child_terminated
2021-06-22 09:27:59.612 [error] <0.424.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.424.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:27:59.612 [error] <0.421.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.421.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.423.0>, {<<"client 127.0.0.1:55686 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.424.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:27:59.612 [error] <0.421.0> Supervisor {<0.421.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.423.0>, {<<"client 127.0.0.1:55686 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.424.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:27:59.612 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.398.0> exit with reason {shutdown,{gen_server,call,[<0.423.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.398.0>},70000]}} in context child_terminated
2021-06-22 09:27:59.644 [error] <0.451.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.451.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:27:59.644 [error] <0.448.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.448.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.450.0>, {<<"client 127.0.0.1:55688 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.451.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:27:59.645 [error] <0.448.0> Supervisor {<0.448.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.450.0>, {<<"client 127.0.0.1:55688 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.451.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:27:59.645 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.425.0> exit with reason {shutdown,{gen_server,call,[<0.450.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.425.0>},70000]}} in context child_terminated
2021-06-22 09:27:59.645 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.425.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:27:59.655 [info] <0.44.0> Application hvac_database exited with reason: shutdown
2021-06-22 09:33:51.008 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:33:51.013 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:33:51.019 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:33:51.019 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:33:51.019 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:33:51.019 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:33:51.083 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:33:51.083 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:33:51.097 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:33:51.104 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:33:51.104 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:33:51.182 [warning] <0.338.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:33:51.346 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:33:51.368 [error] <0.369.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.369.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:33:51.368 [error] <0.366.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.366.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.368.0>, {<<"client 127.0.0.1:57529 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.369.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:33:51.368 [error] <0.366.0> Supervisor {<0.366.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.368.0>, {<<"client 127.0.0.1:57529 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.369.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:33:51.368 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.338.0> exit with reason {shutdown,{gen_server,call,[<0.368.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in context child_terminated
2021-06-22 09:33:51.405 [error] <0.397.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.397.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:33:51.405 [error] <0.394.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.394.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.396.0>, {<<"client 127.0.0.1:57531 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.397.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:33:51.406 [error] <0.394.0> Supervisor {<0.394.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.396.0>, {<<"client 127.0.0.1:57531 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.397.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:33:51.406 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.371.0> exit with reason {shutdown,{gen_server,call,[<0.396.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.371.0>},70000]}} in context child_terminated
2021-06-22 09:33:51.443 [error] <0.424.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.424.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:33:51.443 [error] <0.421.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.421.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.423.0>, {<<"client 127.0.0.1:57533 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.424.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:33:51.444 [error] <0.421.0> Supervisor {<0.421.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.423.0>, {<<"client 127.0.0.1:57533 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.424.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:33:51.444 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.398.0> exit with reason {shutdown,{gen_server,call,[<0.423.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.398.0>},70000]}} in context child_terminated
2021-06-22 09:33:51.478 [error] <0.451.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.451.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:33:51.478 [error] <0.448.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.448.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.450.0>, {<<"client 127.0.0.1:57535 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.451.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:33:51.478 [error] <0.448.0> Supervisor {<0.448.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.450.0>, {<<"client 127.0.0.1:57535 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.451.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:33:51.478 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.425.0> exit with reason {shutdown,{gen_server,call,[<0.450.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.425.0>},70000]}} in context child_terminated
2021-06-22 09:33:51.478 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.425.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:33:51.485 [info] <0.44.0> Application hvac_database exited with reason: shutdown
2021-06-22 09:35:30.073 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:35:30.077 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:35:30.083 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:35:30.083 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:35:30.083 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:35:30.083 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:35:30.150 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:35:30.150 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:35:30.161 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:35:30.168 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:35:30.168 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:35:30.248 [warning] <0.338.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:35:30.408 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:35:30.426 [error] <0.369.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.369.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:35:30.426 [error] <0.366.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.366.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.368.0>, {<<"client 127.0.0.1:51674 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.369.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:35:30.426 [error] <0.366.0> Supervisor {<0.366.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.368.0>, {<<"client 127.0.0.1:51674 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.369.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:35:30.426 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.338.0> exit with reason {shutdown,{gen_server,call,[<0.368.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in context child_terminated
2021-06-22 09:35:30.461 [error] <0.397.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.397.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:35:30.461 [error] <0.394.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.394.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.396.0>, {<<"client 127.0.0.1:51676 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.397.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:35:30.461 [error] <0.394.0> Supervisor {<0.394.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.396.0>, {<<"client 127.0.0.1:51676 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.397.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:35:30.461 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.371.0> exit with reason {shutdown,{gen_server,call,[<0.396.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.371.0>},70000]}} in context child_terminated
2021-06-22 09:35:30.499 [error] <0.424.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.424.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:35:30.499 [error] <0.421.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.421.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.423.0>, {<<"client 127.0.0.1:51678 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.424.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:35:30.499 [error] <0.421.0> Supervisor {<0.421.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.423.0>, {<<"client 127.0.0.1:51678 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.424.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:35:30.499 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.398.0> exit with reason {shutdown,{gen_server,call,[<0.423.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.398.0>},70000]}} in context child_terminated
2021-06-22 09:35:30.533 [error] <0.451.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.451.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:35:30.533 [error] <0.448.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.448.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.450.0>, {<<"client 127.0.0.1:51680 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.451.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:35:30.533 [error] <0.448.0> Supervisor {<0.448.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.450.0>, {<<"client 127.0.0.1:51680 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.451.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:35:30.533 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.425.0> exit with reason {shutdown,{gen_server,call,[<0.450.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.425.0>},70000]}} in context child_terminated
2021-06-22 09:35:30.533 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.425.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:35:30.539 [info] <0.44.0> Application hvac_database exited with reason: shutdown
2021-06-22 09:37:06.851 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:37:06.856 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:37:06.861 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:37:06.861 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:37:06.861 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:37:06.861 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:37:06.925 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:37:06.925 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:37:06.936 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:37:06.940 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:37:06.940 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:37:07.014 [warning] <0.338.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:37:08.802 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'direct' but current is 'topic'">>}},{gen_server,call,[<0.354.0>,{call,{'exchange.declare',0,<<"devices">>,<<"direct">>,false,false,false,false,false,[]},none,<0.338.0>},70000]}} in context start_error
2021-06-22 09:37:08.803 [error] <0.338.0> CRASH REPORT Process <0.338.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'direct' but current is 'topic'">>}},{gen_server,call,[<0.354.0>,{call,{'exchange.declare',0,<<"devices">>,<<"direct">>,false,false,false,false,false,[]},none,<0.338.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:37:56.416 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:37:56.420 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:37:56.426 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:37:56.426 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:37:56.426 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:37:56.426 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:37:56.489 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:37:56.490 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:37:56.500 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:37:56.504 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:37:56.505 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:37:56.593 [warning] <0.323.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:37:58.738 [error] <0.308.0>@Elixir.HVACDatabase.Pubsub.RabbitMQ:setup_queue:25 Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.HVACDatabase.Pubsub.RabbitMQ':setup_queue/0 line 25 in context start_error
2021-06-22 09:37:58.739 [error] <0.323.0>@Elixir.HVACDatabase.Pubsub.RabbitMQ:setup_queue:25 CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.HVACDatabase.Pubsub.RabbitMQ':setup_queue/0 line 25
2021-06-22 09:37:58.739 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACDatabase.Pubsub.RabbitMQ',{{badmatch,{error,econnrefused}},[{'Elixir.HVACDatabase.Pubsub.RabbitMQ',setup_queue,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,25}]},{'Elixir.HVACDatabase.Pubsub.RabbitMQ',init,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,11}]},{'Elixir.GenRMQ.Publisher',init,1,[{file,"lib/publisher.ex"},{line,216}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_s..."},...]},...]}}},...} in application_master:init/4 line 142
2021-06-22 09:38:31.599 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:38:31.604 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:38:31.610 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:38:31.610 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:38:31.610 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:38:31.610 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:38:31.673 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:38:31.673 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:38:31.682 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:38:31.686 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:38:31.686 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:38:31.771 [warning] <0.323.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:38:32.018 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:38:32.037 [error] <0.353.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.353.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:38:32.037 [error] <0.350.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.350.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.352.0>, {<<"client 127.0.0.1:50790 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.353.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:38:32.037 [error] <0.350.0> Supervisor {<0.350.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.352.0>, {<<"client 127.0.0.1:50790 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.353.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:38:32.037 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.323.0> exit with reason {shutdown,{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in context child_terminated
2021-06-22 09:38:32.073 [error] <0.381.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.381.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:38:32.073 [error] <0.378.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.378.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.380.0>, {<<"client 127.0.0.1:50792 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.381.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:38:32.073 [error] <0.378.0> Supervisor {<0.378.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.380.0>, {<<"client 127.0.0.1:50792 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.381.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:38:32.073 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.355.0> exit with reason {shutdown,{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in context child_terminated
2021-06-22 09:38:32.109 [error] <0.408.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.408.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:38:32.109 [error] <0.405.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.405.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.407.0>, {<<"client 127.0.0.1:50794 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.408.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:38:32.109 [error] <0.405.0> Supervisor {<0.405.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.20>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.407.0>, {<<"client 127.0.0.1:50794 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.408.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:38:32.110 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.382.0> exit with reason {shutdown,{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in context child_terminated
2021-06-22 09:38:32.141 [error] <0.435.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.435.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:38:32.141 [error] <0.432.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.432.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.434.0>, {<<"client 127.0.0.1:50796 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.435.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:38:32.141 [error] <0.432.0> Supervisor {<0.432.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.22>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.434.0>, {<<"client 127.0.0.1:50796 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.435.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:38:32.141 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.409.0> exit with reason {shutdown,{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in context child_terminated
2021-06-22 09:38:32.141 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.409.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:38:32.143 [info] <0.44.0> Application hvac_database exited with reason: shutdown
2021-06-22 09:40:28.524 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:40:28.529 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:40:28.535 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:40:28.535 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:40:28.535 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:40:28.535 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:40:28.603 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:40:28.603 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:40:28.615 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:40:28.619 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:40:28.619 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:40:28.707 [warning] <0.338.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:40:28.964 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:40:28.989 [error] <0.338.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.367.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:40:28.999 [error] <0.338.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.367.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:40:28.999 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.338.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.367.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in context child_terminated
2021-06-22 09:40:29.039 [error] <0.370.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.395.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.370.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:40:29.040 [error] <0.370.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.395.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.370.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:40:29.040 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.370.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.395.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.370.0>},70000]}} in context child_terminated
2021-06-22 09:40:29.077 [error] <0.397.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.422.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.397.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:40:29.078 [error] <0.397.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.422.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.397.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:40:29.078 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.397.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.422.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.397.0>},70000]}} in context child_terminated
2021-06-22 09:40:29.114 [error] <0.424.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.449.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.424.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:40:29.115 [error] <0.424.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.449.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.424.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:40:29.115 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.424.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.449.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.424.0>},70000]}} in context child_terminated
2021-06-22 09:40:29.115 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.424.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:40:29.117 [info] <0.44.0> Application hvac_database exited with reason: shutdown
2021-06-22 09:40:49.778 [warning] <0.357.0> Connection (<0.357.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server
2021-06-22 09:40:49.778 [warning] <0.440.0> Connection (<0.440.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server
2021-06-22 09:40:49.778 [warning] <0.413.0> Connection (<0.413.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server
2021-06-22 09:40:49.779 [warning] <0.427.0> Connection (<0.427.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server
2021-06-22 09:40:49.779 [warning] <0.343.0> Connection (<0.343.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server
2021-06-22 09:40:49.782 [warning] <0.373.0> Connection (<0.373.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server
2021-06-22 09:40:49.782 [warning] <0.386.0> Connection (<0.386.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server
2021-06-22 09:40:49.783 [warning] <0.400.0> Connection (<0.400.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server
2021-06-22 09:41:45.910 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:41:45.915 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:41:45.920 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:41:45.921 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:41:45.921 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:41:45.921 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:41:45.987 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:41:45.987 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:41:45.999 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:41:46.004 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:41:46.004 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:41:46.096 [warning] <0.323.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:41:46.330 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:41:46.358 [error] <0.323.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:41:46.366 [error] <0.323.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:41:46.366 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.323.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in context child_terminated
2021-06-22 09:41:46.408 [error] <0.355.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:41:46.408 [error] <0.355.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:41:46.408 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.355.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in context child_terminated
2021-06-22 09:41:46.449 [error] <0.382.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:41:46.450 [error] <0.382.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:41:46.450 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.382.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in context child_terminated
2021-06-22 09:41:46.490 [error] <0.409.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:41:46.492 [error] <0.409.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:41:46.492 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.409.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in context child_terminated
2021-06-22 09:41:46.492 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.409.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:41:46.495 [info] <0.44.0> Application hvac_database exited with reason: shutdown
2021-06-22 09:42:36.520 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:42:36.526 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:42:36.533 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:42:36.533 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:42:36.533 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:42:36.533 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:42:36.601 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:42:36.601 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:42:36.611 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:42:36.617 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:42:36.617 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:42:36.705 [warning] <0.338.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:42:36.973 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.353.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in context start_error
2021-06-22 09:42:36.974 [error] <0.338.0> CRASH REPORT Process <0.338.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.353.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:43:00.232 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:43:00.240 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:43:00.247 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:43:00.248 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:43:00.248 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:43:00.248 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:43:00.313 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:43:00.313 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:43:00.322 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:43:00.326 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:43:00.326 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:43:00.417 [warning] <0.338.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:43:00.616 [error] <0.338.0>@Elixir.AMQP.Exchange:declare:39 CRASH REPORT Process <0.338.0> with 0 neighbours crashed with reason: bad argument in call to erlang:atom_to_binary([{durable,true}], utf8) in 'Elixir.AMQP.Exchange':declare/4 line 39
2021-06-22 09:43:00.616 [error] <0.323.0>@Elixir.AMQP.Exchange:declare:39 Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason bad argument in call to erlang:atom_to_binary([{durable,true}], utf8) in 'Elixir.AMQP.Exchange':declare/4 line 39 in context start_error
2021-06-22 09:43:00.616 [error] <0.321.0> CRASH REPORT Process <0.321.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACDatabase.Pubsub.RabbitMQ',{badarg,[{erlang,atom_to_binary,[[{durable,true}],utf8],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.AMQP.Exchange',declare,4,[{file,"lib/amqp/exchange.ex"},{line,39}]},{'Elixir.HVACDatabase.Pubsub.RabbitMQ',setup_queue,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,32}]},{'Elixir.HVACDatabase.Pubsub.RabbitMQ',init,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,11}]},{'Elixir.GenRMQ.Publisher',...},...]}}},...} in application_master:init/4 line 142
2021-06-22 09:43:23.809 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:43:23.813 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:43:23.820 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:43:23.820 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:43:23.820 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:43:23.820 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:43:23.885 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:43:23.885 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:43:23.898 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:43:23.903 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:43:23.903 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:43:23.987 [warning] <0.338.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:43:24.157 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'devices' in vhost '/': received 'true' but current is 'false'">>}},{gen_server,call,[<0.353.0>,{call,{'exchange.declare',0,<<"devices">>,<<"direct">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in context start_error
2021-06-22 09:43:38.459 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:43:38.465 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:43:38.471 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:43:38.471 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:43:38.471 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:43:38.471 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:43:38.539 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:43:38.539 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:43:38.549 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:43:38.553 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:43:38.553 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:43:38.645 [warning] <0.323.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:43:38.869 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'devices' in vhost '/': received 'true' but current is 'false'">>}},{gen_server,call,[<0.338.0>,{call,{'exchange.declare',0,<<"devices">>,<<"direct">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in context start_error
2021-06-22 09:43:38.870 [error] <0.323.0> CRASH REPORT Process <0.323.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'devices' in vhost '/': received 'true' but current is 'false'">>}},{gen_server,call,[<0.338.0>,{call,{'exchange.declare',0,<<"devices">>,<<"direct">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:43:38.870 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACDatabase.Pubsub.RabbitMQ',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'devices' in vhost '/': received 'true' but current is 'false'">>}},{gen_server,call,[<0.338.0>,{call,{'exchange.declare',0,<<"devices">>,<<"direct">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}}}},{'Elixir.HVACDatabase.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-06-22 09:44:29.830 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:44:29.836 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:44:29.841 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:44:29.842 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:44:29.842 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:44:29.842 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:44:29.910 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:44:29.910 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:44:29.921 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:44:29.926 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:44:29.926 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:44:30.017 [warning] <0.323.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:44:30.272 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:44:30.322 [error] <0.323.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:44:30.332 [error] <0.323.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:44:30.332 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.323.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in context child_terminated
2021-06-22 09:44:30.369 [error] <0.355.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:44:30.370 [error] <0.355.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:44:30.370 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.355.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in context child_terminated
2021-06-22 09:44:30.409 [error] <0.382.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:44:30.409 [error] <0.382.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:44:30.410 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.382.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in context child_terminated
2021-06-22 09:44:30.449 [error] <0.409.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:44:30.450 [error] <0.409.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:44:30.450 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.409.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in context child_terminated
2021-06-22 09:44:30.450 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.409.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:44:30.452 [info] <0.44.0> Application hvac_database exited with reason: shutdown
2021-06-22 09:46:51.043 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:46:51.048 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:46:51.054 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:46:51.054 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:46:51.054 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:46:51.054 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:46:51.121 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:46:51.122 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:46:51.133 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:46:51.137 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:46:51.137 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:46:51.230 [warning] <0.323.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:46:51.505 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:46:51.531 [error] <0.323.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:46:51.543 [error] <0.323.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:46:51.543 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.323.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.352.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.323.0>},70000]}} in context child_terminated
2021-06-22 09:46:51.585 [error] <0.355.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:46:51.585 [error] <0.355.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:46:51.586 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.355.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.380.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.355.0>},70000]}} in context child_terminated
2021-06-22 09:46:51.620 [error] <0.382.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:46:51.621 [error] <0.382.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:46:51.621 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.382.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.407.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.382.0>},70000]}} in context child_terminated
2021-06-22 09:46:51.659 [error] <0.409.0> gen_server 'Elixir.HVACDatabase.Pubsub.RabbitMQ' terminated with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:46:51.660 [error] <0.409.0> CRASH REPORT Process 'Elixir.HVACDatabase.Pubsub.RabbitMQ' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in gen_server:call/3 line 247
2021-06-22 09:46:51.660 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.409.0> exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in context child_terminated
2021-06-22 09:46:51.660 [error] <0.308.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.409.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:46:51.663 [info] <0.44.0> Application hvac_database exited with reason: shutdown
2021-06-22 09:47:33.850 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:47:33.854 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:47:33.861 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:47:33.861 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:47:33.861 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:47:33.861 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:47:33.933 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:47:33.933 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:47:33.943 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:47:33.948 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:47:33.948 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:47:34.032 [warning] <0.338.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:47:34.280 [error] <0.323.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'devices' in vhost '/': received 'topic' but current is 'direct'">>}},{gen_server,call,[<0.353.0>,{call,{'exchange.declare',0,<<"devices">>,<<"topic">>,false,true,false,false,false,[]},none,<0.338.0>},70000]}} in context start_error
2021-06-22 09:48:42.284 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:48:42.289 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:48:42.294 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:48:42.294 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:48:42.294 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:48:42.295 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:48:42.364 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:48:42.364 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:48:42.374 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:48:42.380 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:48:42.380 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:48:42.476 [warning] <0.323.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:48:42.733 [info] <0.44.0> Application hvac_database started on node nonode@nohost
2021-06-22 09:49:08.551 [info] <0.44.0> Application lager started on node nonode@nohost
2021-06-22 09:49:08.556 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-06-22 09:49:08.562 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-06-22 09:49:08.562 [info] <0.44.0> Application tools started on node nonode@nohost
2021-06-22 09:49:08.563 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-06-22 09:49:08.563 [info] <0.44.0> Application recon started on node nonode@nohost
2021-06-22 09:49:08.630 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-06-22 09:49:08.630 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-06-22 09:49:08.640 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-06-22 09:49:08.645 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-06-22 09:49:08.645 [info] <0.44.0> Application gen_rmq started on node nonode@nohost
2021-06-22 09:49:08.734 [warning] <0.323.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-06-22 09:49:08.980 [info] <0.44.0> Application hvac_database started on node nonode@nohost
